#pragma once

//sign in:
#define	SERVER_SIGN_IN_SUCCESS "1020"
#define	SERVER_SIGN_IN_WRONG_DETAILS "1021"
#define	SERVER_SIGN_IN_ALLREADY_CONNECTAED "1022"

//sign up:
#define	SERVER_SIGN_UP_SUCCESS "1040"
#define SERVER_SIGN_UP_PASS_ILEGAL "1041"
#define SERVER_SIGN_UP_USERNAME_ALLREDY_EXIST "1042"
#define SERVER_SIGN_UP_USERNAME_ILEGAL "1043"
#define SERVER_SIGN_UP_OTHER "1044"

//join room:
#define SERVER_JOIN_ROOM_SECCESS "1100"
#define SERVER_JOIN_ROOM_FULL "1101"
#define SERVER_JOIN_ROOM_NOT_EXIST "1102"

//creat room:
#define SERVER_CREAT_ROOM_SECCESS "1140"
#define SERVER_CREAT_ROOM_FAIL "1141"


#define SERVER_SEND_QUESTION "118"
#define SERVER_ANSWER "120"
#define SERVER_CLOSE_ROOM "116"
#define SERVER_GET_EXIST_ROOMS "106"
#define SERVER_USER_IN_ROOM "108"
#define SERVER_LEAVE_ROOM "1120"
#define SERVER_END_GAME "121"
#define SERVER_BEST_SCORES "124"
#define SERVER_PERSONAL_STATUS "126"